### ISSUE TITLE
Required docker-compose version too new for Ubuntu 16.04

### ISSUE THREAD

**Issue by rbialon** [Wegi/pogo-cruncher#11]
Using Ubuntu 16.04's regular package repositories, `docker-compose build` fails with the following error message:

```
✔ pogo-cruncher master@5c651f2$ docker-compose build
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

Ubuntu 16.04's version of `docker-compose` is
```
✔ pogo-cruncher master@5c651f2$ docker-compose -v
docker-compose version 1.5.2, build unknown
```
whereas the `version: '2'` in `docker-compose.yml` requires version 1.6+ ([See here](https://docs.docker.com/compose/compose-file/#/version-2)).

A possible solution is to not support docker-compose <= 1.6.x.
I will try to work out if it is also compatible with a version 1 `docker-compose.yml`.

**Comment by rbialon** [comment]
I created a version 1 `docker-compose.yml` for anyone who's interested: [Here](https://gist.github.com/rbialon/baf65ee2a4d2414ec6f4a6f45114acac).

The better solution is to ditch `docker-compose` from Ubuntu's package repositories and install it through pip
```
pip install docker-compose
```
This retrieves the latest version of `docker-compose`, which currently is 1.7.1.

**Comment by n2o** [comment]
I do not like the solution to use version 1 since it is old and docker compose should be installed via pip.
