### ISSUE TITLE
frontend missing bower_components and clojurescript output

### ISSUE THREAD

**Issue by rbialon** [Wegi/pogo-cruncher#12]
Running `docker-compose build` and `docker-compose up`, everything seems to be okay from the logs.
The two containers start up and the SimpleHttpServer is listening on port 8888.

But, upon connecting, I get 404's for nearly every resource:

> ✔ pogo-cruncher master@5c651f2$ docker-compose up
Creating network "pogocruncher_default" with the default driver
Recreating pogocruncher_frontend_1
Recreating pogocruncher_backend_1
Attaching to pogocruncher_backend_1, pogocruncher_frontend_1
backend_1   |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET / HTTP/1.1" 200 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /bower_components/bootswatch-dist/css/bootstrap.min.css HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /bower_components/fontawesome/css/font-awesome.min.css HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /css/style.css HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /bower_components/jquery/dist/jquery.min.js HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /js/compiled/cruncher.js HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 -
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] code 404, message File not found
frontend_1  | 172.18.0.1 - - [26/Jul/2016 05:41:23] "GET /js/compiled/cruncher.js HTTP/1.1" 404 -

Attaching to the frontend container through `docker exec -it pogocruncher_frontend_1 /bin/bash` and re-running the following parts from the frontend's Dockerfile:
```
cd /frontend/
GIT_DIR=/tmp bower install --allow-root
lein deps
lein cljsbuild once min
sass css/style.sass css/style.css --style compressed
cd resources/public/
sass css/style.sass css/style.css --style compressed
rm -rf .sass-cache
```
I end up with a working pogocruncher.
I suppose that somehow the frontend container is created without running the commands from it's Dockerfile.

```
✔ pogo-cruncher master@5c651f2$ docker -v
Docker version 1.10.3, build 20f81dd
✔ pogo-cruncher master@5c651f2$ docker-compose -v
docker-compose version 1.7.1, build 6c29830
```

**Comment by Wegi** [comment]
In the compose file the mounting of the /frontend folder over the container-version of /frontend killed all the container files during sync. Please report if it works with the newest version.

**Comment by rbialon** [comment]
I can confirm that using edea1c0494ddd21cd5919b859870afe89f8e658c works as expected.
