### ISSUE TITLE
Not deleting

### ISSUE THREAD

**Issue by SeeingBlue** [Wegi/pogo-cruncher#21]
```
backend_1   | 172.18.0.1 - - [28/Jul/2016 14:58:07] "OPTIONS /api/login HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [28/Jul/2016 14:58:08] "POST /api/login HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [28/Jul/2016 14:58:12] "GET /api/pokemon HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [28/Jul/2016 15:02:57] "OPTIONS /api/pokemon/delete HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [28/Jul/2016 15:02:57] "POST /api/pokemon/delete HTTP/1.1" 400 -
``` 
This is the request for my pokemon list, which works. The second request is when I hit delete on multiple pokemon. It sends 1 delete but not a single pokemon is deleted.

**Comment by Wegi** [comment]
How many are you trying to delete? It sleeps a few seconds between every pokemon to not appear as a bot. Did you try deleting just one, does that work?

**Comment by SeeingBlue** [comment]
Roughly 125. I did not try just 1. I have since used another program to mass transfer. I saw that you wait 2 seconds or so, but that log just sat there, even after several minutes, nothing else happened.

**Comment by Wegi** [comment]
125 would be between 4 and 7 minutes. I'll will add an option for instant deletion in the next full release.

There is currently no progress bar also.
Feel free to reopen the ticket, if you make further test.

**Comment by SeeingBlue** [comment]
Ok. I was expecting some type of indicator of progress or at least new entries in the console. I also noticed that your in-game inventory is a little lagged. Doesn't updated very often which lead me to believe nothing was deleting.
