### ISSUE TITLE
Feature Request: evolving pokemon?

### ISSUE THREAD

**Issue by weblue** [Wegi/pogo-cruncher#25]
Adding the feature to evolve then transfer would be nice. I'm not entirely sure if that's what "crunching" already does. I would love to help with implementing the feature if I could be shown the right direction to go; Python's not my primary language.

**Comment by weblue** [comment]
I'd be happy to try to learn to help coding with this if you'd be interested in talking a bit. I can see a couple of features that probably wouldn't be too difficult to add.

**Comment by Wegi** [comment]
Thats deffinitely a possible thing to add. If you want to look at a starting point you can look at the pgoapi library im using. Its the point which communicates with the Pokemon Server. 

Feel free to ask further if you have any questions.

**Comment by Wegi** [comment]
duplicate of another issue #16
