### ISSUE TITLE
Error when starting using Windows

### ISSUE THREAD

**Issue by Icantthinkofanyname** [Wegi/pogo-cruncher#39]
Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Restarting with stat
Debugger is active!
Debugger pin code: 144-805-040 Exception in thread Thread-1: Traceback (most recent call last): File "C:\python35\lib\threading.py", line 914, in bootstrap_inner self.run() File "C:\python35\lib\threading.py", line 862, in run self._target(self._args, *self._kwargs) File "C:\python35\lib\site-packages\werkzeug\serving.py", line 656, in inner fd=fd) File "C:\python35\lib\site-packages\werkzeug\serving.py", line 550, in make_se rver passthrough_errors, ssl_context, fd=fd) File "C:\python35\lib\site-packages\werkzeug\serving.py", line 462, in __init _ socket.SOCK_STREAM) File "C:\python35\lib\socket.py", line 450, in fromfd nfd = dup(fd) OSError: [WinError 10038] An operation was attempted on something that is not a socket

**Comment by Wegi** [comment]
Should be fixed in commit 429f453 . Try the newest app.py. If this does not solve the problem, please reopen the issue.

**Comment by Icantthinkofanyname** [comment]
Just want to report the issue is fixed.

There is a minor error in reporting when deleting pokemon

-
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20
Deleted Pokemon 0 out of 20

**Comment by Wegi** [comment]
Thank you, fixed that as well in commit 184122a
